export const CHAIN_ID = {
  POLYGON_MUMBAI: 80001,
};

export const ERROR_CODE = {
  CALL_EXCEPTION: 'CALL_EXCEPTION',
  REPLACEMENT_UNDERPRICED: 'REPLACEMENT_UNDERPRICED',
  TIMEOUT: 'TIMEOUT',
  TRANSACTION_REPLACED: 'TRANSACTION_REPLACED',
};
